# Generated by Django 5.0.4 on 2024-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('image', models.URLField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
